Jan 5 12:05:41 PM  ==> Cloning from https://github.com/d3t3rminant/python-web-microblog...
Jan 5 12:05:42 PM  ==> Checking out commit 8611b085c1ccdb9ea8d7b16d6a9d2c340bf88a60 in branch main
Jan 5 12:06:01 PM  ==> Using Python version: 3.10.8
Jan 5 12:06:07 PM  ==> Running build command 'pip install -r requirements.txt'...
Jan 5 12:06:08 PM  Collecting click==8.1.3
Jan 5 12:06:08 PM    Downloading click-8.1.3-py3-none-any.whl (96 kB)
Jan 5 12:06:08 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 2.1 MB/s eta 0:00:00
Jan 5 12:06:08 PM  Collecting colorama==0.4.6
Jan 5 12:06:08 PM    Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Jan 5 12:06:08 PM  Collecting dnspython==2.2.1
Jan 5 12:06:08 PM    Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
Jan 5 12:06:08 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 14.8 MB/s eta 0:00:00
Jan 5 12:06:08 PM  Collecting Flask==2.2.2
Jan 5 12:06:08 PM    Downloading Flask-2.2.2-py3-none-any.whl (101 kB)
Jan 5 12:06:08 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.5/101.5 kB 2.1 MB/s eta 0:00:00
Jan 5 12:06:08 PM  Collecting itsdangerous==2.1.2
Jan 5 12:06:08 PM    Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Jan 5 12:06:08 PM  Collecting Jinja2==3.1.2
Jan 5 12:06:08 PM    Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
Jan 5 12:06:08 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 24.1 MB/s eta 0:00:00
Jan 5 12:06:09 PM  Collecting MarkupSafe==2.1.1
Jan 5 12:06:09 PM    Downloading MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Jan 5 12:06:09 PM  Collecting numpy==1.23.3
Jan 5 12:06:09 PM    Downloading numpy-1.23.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Jan 5 12:06:09 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 64.8 MB/s eta 0:00:00
Jan 5 12:06:10 PM  Collecting pandas==1.5.0
Jan 5 12:06:10 PM    Downloading pandas-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Jan 5 12:06:10 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 47.5 MB/s eta 0:00:00
Jan 5 12:06:11 PM  Collecting pymongo==4.3.3
Jan 5 12:06:11 PM    Downloading pymongo-4.3.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (492 kB)
Jan 5 12:06:11 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.9/492.9 kB 14.3 MB/s eta 0:00:00
Jan 5 12:06:11 PM  Collecting python-dateutil==2.8.2
Jan 5 12:06:11 PM    Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Jan 5 12:06:11 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 12.1 MB/s eta 0:00:00
Jan 5 12:06:11 PM  Collecting pytz==2022.4
Jan 5 12:06:11 PM    Downloading pytz-2022.4-py2.py3-none-any.whl (500 kB)
Jan 5 12:06:11 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 500.8/500.8 kB 8.6 MB/s eta 0:00:00
Jan 5 12:06:11 PM  Collecting six==1.16.0
Jan 5 12:06:11 PM    Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Jan 5 12:06:11 PM  Collecting Werkzeug==2.2.2
Jan 5 12:06:11 PM    Downloading Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Jan 5 12:06:11 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.7/232.7 kB 5.6 MB/s eta 0:00:00
Jan 5 12:06:11 PM  Collecting gunicorn
Jan 5 12:06:11 PM    Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
Jan 5 12:06:11 PM       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.2 MB/s eta 0:00:00
Jan 5 12:06:11 PM  Requirement already satisfied: setuptools>=3.0 in ./.venv/lib/python3.10/site-packages (from gunicorn->-r requirements.txt (line 15)) (63.2.0)
Jan 5 12:06:12 PM  Installing collected packages: pytz, six, numpy, MarkupSafe, itsdangerous, gunicorn, dnspython, colorama, click, Werkzeug, python-dateutil, pymongo, Jinja2, pandas, Flask
Jan 5 12:06:23 PM  Successfully installed Flask-2.2.2 Jinja2-3.1.2 MarkupSafe-2.1.1 Werkzeug-2.2.2 click-8.1.3 colorama-0.4.6 dnspython-2.2.1 gunicorn-20.1.0 itsdangerous-2.1.2 numpy-1.23.3 pandas-1.5.0 pymongo-4.3.3 python-dateutil-2.8.2 pytz-2022.4 six-1.16.0
Jan 5 12:06:23 PM  
Jan 5 12:06:23 PM  [notice] A new release of pip available: 22.2.2 -> 22.3.1
Jan 5 12:06:23 PM  [notice] To update, run: pip install --upgrade pip
Jan 5 12:06:24 PM  ==> Generating container image from build. This may take a few minutes...
Jan 5 12:08:49 PM  ==> Uploading build...
Jan 5 12:09:11 PM  ==> Build uploaded in 16s
Jan 5 12:09:12 PM  ==> Build successful 🎉
Jan 5 12:09:12 PM  ==> Deploying...
Jan 5 12:09:50 PM  ==> Starting service with 'gunicorn app:app'
Jan 5 12:09:55 PM  Traceback (most recent call last):
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 402, in import_app
Jan 5 12:09:55 PM      app = getattr(mod, name)
Jan 5 12:09:55 PM  AttributeError: module 'app' has no attribute 'app'
Jan 5 12:09:55 PM  
Jan 5 12:09:55 PM  During handling of the above exception, another exception occurred:
Jan 5 12:09:55 PM  
Jan 5 12:09:55 PM  Traceback (most recent call last):
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
Jan 5 12:09:55 PM      sys.exit(run())
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
Jan 5 12:09:55 PM      WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
Jan 5 12:09:55 PM      super().run()
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
Jan 5 12:09:55 PM      Arbiter(self).run()
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
Jan 5 12:09:55 PM      self.setup(app)
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
Jan 5 12:09:55 PM      self.app.wsgi()
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 5 12:09:55 PM      self.callable = self.load()
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jan 5 12:09:55 PM      return self.load_wsgiapp()
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jan 5 12:09:55 PM      return util.import_app(self.app_uri)
Jan 5 12:09:55 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 406, in import_app
Jan 5 12:09:55 PM      raise AppImportError("Failed to find attribute %r in %r." % (name, module))
Jan 5 12:09:55 PM  gunicorn.errors.AppImportError: Failed to find attribute 'app' in 'app'.
Jan 5 12:10:10 PM  ==> Starting service with 'gunicorn app:app'
Jan 5 12:10:15 PM  Traceback (most recent call last):
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 402, in import_app
Jan 5 12:10:15 PM      app = getattr(mod, name)
Jan 5 12:10:15 PM  AttributeError: module 'app' has no attribute 'app'
Jan 5 12:10:15 PM  
Jan 5 12:10:15 PM  During handling of the above exception, another exception occurred:
Jan 5 12:10:15 PM  
Jan 5 12:10:15 PM  Traceback (most recent call last):
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
Jan 5 12:10:15 PM      sys.exit(run())
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
Jan 5 12:10:15 PM      WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
Jan 5 12:10:15 PM      super().run()
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
Jan 5 12:10:15 PM      Arbiter(self).run()
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
Jan 5 12:10:15 PM      self.setup(app)
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
Jan 5 12:10:15 PM      self.app.wsgi()
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 5 12:10:15 PM      self.callable = self.load()
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jan 5 12:10:15 PM      return self.load_wsgiapp()
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jan 5 12:10:15 PM      return util.import_app(self.app_uri)
Jan 5 12:10:15 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 406, in import_app
Jan 5 12:10:15 PM      raise AppImportError("Failed to find attribute %r in %r." % (name, module))
Jan 5 12:10:15 PM  gunicorn.errors.AppImportError: Failed to find attribute 'app' in 'app'.
Jan 5 12:10:41 PM  ==> Starting service with 'gunicorn app:app'
Jan 5 12:10:45 PM  Traceback (most recent call last):
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 402, in import_app
Jan 5 12:10:45 PM      app = getattr(mod, name)
Jan 5 12:10:45 PM  AttributeError: module 'app' has no attribute 'app'
Jan 5 12:10:45 PM  
Jan 5 12:10:45 PM  During handling of the above exception, another exception occurred:
Jan 5 12:10:45 PM  
Jan 5 12:10:45 PM  Traceback (most recent call last):
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
Jan 5 12:10:45 PM      sys.exit(run())
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
Jan 5 12:10:45 PM      WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
Jan 5 12:10:45 PM      super().run()
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
Jan 5 12:10:45 PM      Arbiter(self).run()
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
Jan 5 12:10:45 PM      self.setup(app)
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
Jan 5 12:10:45 PM      self.app.wsgi()
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 5 12:10:45 PM      self.callable = self.load()
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jan 5 12:10:45 PM      return self.load_wsgiapp()
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jan 5 12:10:45 PM      return util.import_app(self.app_uri)
Jan 5 12:10:45 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 406, in import_app
Jan 5 12:10:45 PM      raise AppImportError("Failed to find attribute %r in %r." % (name, module))
Jan 5 12:10:45 PM  gunicorn.errors.AppImportError: Failed to find attribute 'app' in 'app'.
Jan 5 12:11:18 PM  ==> Starting service with 'gunicorn app:app'
Jan 5 12:11:22 PM  Traceback (most recent call last):
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 402, in import_app
Jan 5 12:11:22 PM      app = getattr(mod, name)
Jan 5 12:11:22 PM  AttributeError: module 'app' has no attribute 'app'
Jan 5 12:11:22 PM  
Jan 5 12:11:22 PM  During handling of the above exception, another exception occurred:
Jan 5 12:11:22 PM  
Jan 5 12:11:22 PM  Traceback (most recent call last):
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
Jan 5 12:11:22 PM      sys.exit(run())
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
Jan 5 12:11:22 PM      WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
Jan 5 12:11:22 PM      super().run()
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
Jan 5 12:11:22 PM      Arbiter(self).run()
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
Jan 5 12:11:22 PM      self.setup(app)
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
Jan 5 12:11:22 PM      self.app.wsgi()
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 5 12:11:22 PM      self.callable = self.load()
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jan 5 12:11:22 PM      return self.load_wsgiapp()
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jan 5 12:11:22 PM      return util.import_app(self.app_uri)
Jan 5 12:11:22 PM    File "/opt/render/project/src/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 406, in import_app
Jan 5 12:11:22 PM      raise AppImportError("Failed to find attribute %r in %r." % (name, module))
Jan 5 12:11:22 PM  gunicorn.errors.AppImportError: Failed to find attribute 'app' in 'app'.